name: Scheduled Database Cleanup (Bun)

on:
  schedule:
    - cron: '59 23 * * 0'
  workflow_dispatch:

jobs:
  run_cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run cleanup script
        run: bun run src/lib/server/scheduled-tasks/cleanupOldData.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          VITE_CLOUDINARY_CLOUD_NAME: ${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }}
          VITE_CLOUDINARY_API_KEY: ${{ secrets.VITE_CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
